### ISSUE TITLE
似乎不能使用

### ISSUE THREAD

**Issue by NewbieXvwu** [xingchuanzhen/Minecraft-Unlock#4]
Minecraft 目前在你的帐户中不可用。请确保你已登录到 Microsoft Store，然后重试。如果需要，可以使用以下错误代码: 0x803F8001

Minecraft 版本：1.18.203.0（x64）

程序已经成功替换文件，可是游戏仍无法打开。我要怎么做？

**Comment by xingchuanzhen** [comment]
程序开发后经过多次测速，是完全可以使用的，按照这个提示来看，应该是您没有登录Microsoft Store账号导致，您可以尝试在登录Microsoft Store账号后重启电脑然后重试，看看问题能不能够被正常解决，谢谢！

**Comment by NewbieXvwu** [comment]
![image](https://user-images.githubusercontent.com/87637612/149649833-60ee5fb5-ed4d-4a62-8ca9-5e84f62bef2d.png)
我已在微软商店登录，似乎仍没用……是否要在设置登录？我想使用本地账户……

**Comment by xingchuanzhen** [comment]
> ![image](https://user-images.githubusercontent.com/87637612/149649833-60ee5fb5-ed4d-4a62-8ca9-5e84f62bef2d.png) 我已在微软商店登录，似乎仍没用……是否要在设置登录？我想使用本地账户……

请问您使用的是本地安装包安装还是在商店里在线安装？如果是本地安装的话请先将软件卸载然后移至https://www.xbox.com/zh-CN/games/store/minecraft-for-windows/9NBLGGH2JHXJ/0010
上重新下载安装，谢谢！
