### ISSUE TITLE
工具部分Bug

### ISSUE THREAD

**Issue by sfc9982** [xingchuanzhen/Minecraft-Unlock#5]
- 还原dll时使用工具内置资源中的dll，但不同版本的Windows这个dll是不一样的，导致系统验证hash时出错，会导致未预期的`sfc`, `dism`报错，建议加上版本特判，**并在运行时提醒用户手动备份**。
- 由于系统权限问题，可能替换不成功，可以参考下`takeown`和`icacls`命令的用法
  - `takeown /f C:\Windows\System32\Windows.ApplicationModel.Store.dll`
  - `icacls C:\Windows\System32\Windows.ApplicationModel.Store.dll /grant administrators:F`

正在审计代码，可能提PR

**Comment by sfc9982** [comment]
[Original_DLL.zip](https://github.com/xingchuanzhen/Minecraft-Unlock/files/7876529/Original_DLL.zip)
这个是**Windows 11**各个通道的**原**DLL文件

**Comment by xingchuanzhen** [comment]
不同的DLL确实是一个问题，源文件的DLL是从我的系统中提取的，目前解决方案可以使用控制台命令FSC的SCANFILE命令来定位和修复指定文件，经过我都验证他是可行的，他或许会在后续版本中添加(如果我不懒的话)

文件权限方面我使用了IObitUnlocker驱动将其解决，先删除源文件，然后移动新文件，但移动文件仍采用CMD命令的方式移动，收到的反馈大部分都是卡在这一步了，经过研究后发现是操作被Windows Defender拦截了，关闭后程序正常运行

感谢您提出的问题！

**Comment by sfc9982** [comment]
`SFC`命令在某些机器上可能无法修复，可以关注下。

谢谢

**Comment by xingchuanzhen** [comment]
> `SFC`命令在某个机器上可能无法修复，可以关注下。
> 
> 谢谢

那就只能使用时备份用户源文件，但是可能会因为用户不当操作会容易造成源文件的丢失，导致无法还原，这个问题还有待解决。

**Comment by xingchuanzhen** [comment]
> [Original_DLL11](https://github.com/xingchuanzhen/Minecraft-Unlock/files/7876529/Original_DLL.zip)任务包，但这个DLL文件是一款Windows 10的 开源文件**，****需要**测试**Windows ****10**********

这些文件在我计算了它们的MD5后发现都是一样的，它们都是同一个文件
![Snipaste_2022-01-16_18-50-25](https://user-images.githubusercontent.com/78350684/149656955-0f28bc04-aeb0-4314-b828-f906c535c30a.png)

**Comment by sfc9982** [comment]
> > [Original_DLL11](https://github.com/xingchuanzhen/Minecraft-Unlock/files/7876529/Original_DLL.zip)任务包，但这个DLL文件是一款Windows 10的 开源文件**，****需要**测试**Windows ****10**********
> 
> 这些文件在我计算了它们的MD5后发现都是一样的，它们都是同一个文件 ![Snipaste_2022-01-16_18-50-25](https://user-images.githubusercontent.com/78350684/149656955-0f28bc04-aeb0-4314-b828-f906c535c30a.png)

我粗心了，但是用了工具还原后还是提示损坏，用我这个Zip里的就OK

**Comment by xingchuanzhen** [comment]
> 

从签名时间来看你提供的是比我程序资源文件中的源文件新，并且文件的MD5也不相同，可能我提供的是win10版本的，而你提供的是win11版本，它们互不兼容

**Comment by xingchuanzhen** [comment]
> > > [Original_DLL1111](https://github.com/xingchuanzhen/Minecraft-Unlock/files/7876529/Original_DLL.zip)，但这个DLL文件是任务Windows 10的开源文件**，****需要**测试**Windows ****10******** **
> > 
> > 
> > 这些文件在我计算出来的 MD5 后都是一样的，它们都发现了同一个文件 ![Snipaste_2022-01-16_18-50-25](https://user-images.githubusercontent.com/78350684/149656955-0f28bc04-aeb0-4314-b828-f906c535c30a.png)
> 
> 我粗心还原了，但是用了工具后还是提示损坏，用我这个Zip里的就OK了

签名时间看你提供的是不是我的程序资源文件中的新文件，而文件是win10版本的，而你提供的是win11版本的，它们提供的不是我的程序源文件5

**Comment by xingchuanzhen** [comment]
> > > [Original_DLL11](https://github.com/xingchuanzhen/Minecraft-Unlock/files/7876529/Original_DLL.zip)任务包，但这个DLL文件是一款Windows 10的 开源文件**，****需要**测试**Windows ****10**********
> > 
> > 
> > 这些文件在我计算了它们的MD5后发现都是一样的，它们都是同一个文件 ![Snipaste_2022-01-16_18-50-25](https://user-images.githubusercontent.com/78350684/149656955-0f28bc04-aeb0-4314-b828-f906c535c30a.png)
> 
> 我粗心了，但是用了工具还原后还是提示损坏，用我这个Zip里的就OK

从签名时间上来看你提供的更新，我提供的是win10版本的文件，而你的是win11版本，它们两个互不相同，也互不兼容

**Comment by sfc9982** [comment]
@xingchuanzhen 那可以对系统版本做个判断。用不同的dll替换，或者使用`sfc`

**Comment by xingchuanzhen** [comment]
> @xingchuanzhen 那可以对系统版本做个判断。用不同的dll替换，或者使用`sfc`

我觉得使用SFC更加简便，下一个版本中会添加他
