### ISSUE TITLE
新版本不能用了

### ISSUE THREAD

**Issue by lanjiachen** [xingchuanzhen/Minecraft-Unlock#6]
老版本打开速度很快，新版本win10版本21H2打开半天没反应·

**Comment by lanjiachen** [comment]
有用的是Minecraft Start Up.exe，unlock没有用哎

**Comment by xingchuanzhen** [comment]
可以尝试重启系统，看看问题有没有得到解决，随便告知一下程序版本号

**Comment by xingchuanzhen** [comment]
感兴趣的话可以移至新版本页面 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI
