### ISSUE TITLE
WIN11无法使用

### ISSUE THREAD

**Issue by ZOUQUAN-A** [xingchuanzhen/Minecraft-Unlock#7]
WIN11系统下无法使用此软件，附日志
log：
[18:24:38]: 程序启动...
[18:24:40]: 开始替换文件...
[18:24:40]: 释放资源...
[18:24:40]: 加载驱动...
[18:24:40]: 删除原始文件...
[18:24:40]: 开始移动文件...
[18:24:40]: 已复制0个文件。
[18:24:40]: 已复制0个文件。
[18:24:40]: 执行成功!!!

**Comment by xingchuanzhen** [comment]
部分情况下需要关闭Windows Defender，如果还有其他杀毒软件也请将其关闭

**Comment by xingchuanzhen** [comment]
感兴趣的话可以参照另一种解锁方式 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI

**Comment by ZOUQUAN-A** [comment]
> 感兴趣的话可以参照另一种解锁方式 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI

希望可以通过此项目提供的操作达到永久解锁的效果，但是在关闭Windows Defender的所有防护功能的情况下仍然为如下日志：
[19:13:20]: 程序启动...
[19:13:21]: 开始替换文件...
[19:13:21]: 释放资源...
[19:13:21]: 加载驱动...
[19:13:21]: 删除原始文件...
[19:13:21]: 开始移动文件...
[19:13:21]: 已复制0个文件。
[19:13:21]: 已复制0个文件。
[19:13:21]: 执行成功!!!

**Comment by xingchuanzhen** [comment]
你可以尝试手动替换某些文件，文件位置在项目中的Windows11目录下，解压后包含两个Dll文件，将它们替换到所对应的文件夹中，如果需要，我可以为你提供帮助。

**Comment by xingchuanzhen** [comment]
> > 感兴趣的话可以参照另一种解锁方式 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI
> 
> 希望可以通过此项目提供的操作达到永久解锁的效果，但是在关闭Windows Defender的所有防护功能的情况下仍然为如下日志： [19:13:20]: 程序启动... [19:13:21]: 开始替换文件... [19:13:21]: 释放资源... [19:13:21]: 加载驱动... [19:13:21]: 删除原始文件... [19:13:21]: 开始移动文件... [19:13:21]: 已复制0个文件。 [19:13:21]: 已复制0个文件。 [19:13:21]: 执行成功!!!

很抱歉项目是通过动态修改内存的方式来绕过验证，无法将其达到永久效果，除非修改安装包文件，那样的话又会由于不受信任的证书导致无法安装

**Comment by ZOUQUAN-A** [comment]
> 

希望获得文件目录，谢谢

**Comment by ZOUQUAN-A** [comment]
> > > 感兴趣的话可以参照另一种解锁方式 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI
> > 
> > 
> > 希望可以通过此项目提供的操作达到永久解锁的效果，但是在关闭Windows Defender的所有防护功能的情况下仍然为如下日志： [19:13:20]: 程序启动... [19:13:21]: 开始替换文件... [19:13:21]: 释放资源... [19:13:21]: 加载驱动... [19:13:21]: 删除原始文件... [19:13:21]: 开始移动文件... [19:13:21]: 已复制0个文件。 [19:13:21]: 已复制0个文件。 [19:13:21]: 执行成功!!!
> 
> 很抱歉项目是通过动态修改内存的方式来绕过验证，无法将其达到永久效果，除非修改安装包文件，那样的话又会由于不受信任的证书导致无法安装

Unlock这个项目不是通过修改文件来达到永久效果吗？

**Comment by xingchuanzhen** [comment]
> > 
> 
> 希望获得文件目录，谢谢

将解压后文件夹下的Windows.ApplicationModel.Store.dll文件复制并替换到C:\Windows\System32和C:\Windows\SysWOW64目录下

**Comment by xingchuanzhen** [comment]
> > > > 感兴趣的话可以参照另一种解锁方式 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI
> > > 
> > > 
> > > 希望可以通过此项目提供的操作达到永久解锁的效果，但是在关闭Windows Defender的所有防护功能的情况下仍然为如下日志： [19:13:20]: 程序启动... [19:13:21]: 开始替换文件... [19:13:21]: 释放资源... [19:13:21]: 加载驱动... [19:13:21]: 删除原始文件... [19:13:21]: 开始移动文件... [19:13:21]: 已复制0个文件。 [19:13:21]: 已复制0个文件。 [19:13:21]: 执行成功!!!
> > 
> > 
> > 很抱歉项目是通过动态修改内存的方式来绕过验证，无法将其达到永久效果，除非修改安装包文件，那样的话又会由于不受信任的证书导致无法安装
> 
> Unlock这个项目不是通过修改文件来达到永久效果吗？

这个项目可以达到永久效果，另一个项目不可以

**Comment by ZOUQUAN-A** [comment]
> > > > > 感兴趣的话可以参照另一种解锁方式 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI
> > > > 
> > > > 
> > > > 希望可以通过此项目提供的操作达到永久解锁的效果，但是在关闭Windows Defender的所有防护功能的情况下仍然为如下日志： [19:13:20]: 程序启动... [19:13:21]: 开始替换文件... [19:13:21]: 释放资源... [19:13:21]: 加载驱动... [19:13:21]: 删除原始文件... [19:13:21]: 开始移动文件... [19:13:21]: 已复制0个文件。 [19:13:21]: 已复制0个文件。 [19:13:21]: 执行成功!!!
> > > 
> > > 
> > > 很抱歉项目是通过动态修改内存的方式来绕过验证，无法将其达到永久效果，除非修改安装包文件，那样的话又会由于不受信任的证书导致无法安装
> > 
> > 
> > Unlock这个项目不是通过修改文件来达到永久效果吗？
> 
> 这个项目可以达到永久效果，另一个项目不可

> > > > > 感兴趣的话可以参照另一种解锁方式 https://github.com/xingchuanzhen/Minecraft_Memory_Bypass_GUI
> > > > 
> > > > 
> > > > 希望可以通过此项目提供的操作达到永久解锁的效果，但是在关闭Windows Defender的所有防护功能的情况下仍然为如下日志： [19:13:20]: 程序启动... [19:13:21]: 开始替换文件... [19:13:21]: 释放资源... [19:13:21]: 加载驱动... [19:13:21]: 删除原始文件... [19:13:21]: 开始移动文件... [19:13:21]: 已复制0个文件。 [19:13:21]: 已复制0个文件。 [19:13:21]: 执行成功!!!
> > > 
> > > 
> > > 很抱歉项目是通过动态修改内存的方式来绕过验证，无法将其达到永久效果，除非修改安装包文件，那样的话又会由于不受信任的证书导致无法安装
> > 
> > 
> > Unlock这个项目不是通过修改文件来达到永久效果吗？
> 
> 这个项目可以达到永久效果，另一个项目不可以

非常感谢作者提供帮助！
